# Generated by Django 4.2 on 2023-05-03 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('DoctorID', models.IntegerField()),
                ('PatientID', models.IntegerField()),
                ('Detail', models.CharField(max_length=100)),
                ('DateOfAppointment', models.DateField()),
                ('TimeOfAppointment', models.TimeField()),
                ('Preferred_Time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('DepID', models.AutoField(primary_key=True, serialize=False)),
                ('DepName', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Home.user')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
            ],
            bases=('Home.user',),
        ),
        migrations.CreateModel(
            name='Secretary',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Home.user')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('DepID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.department')),
            ],
            bases=('Home.user',),
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Home.user')),
                ('specialty', models.CharField(max_length=100)),
                ('workDate', models.DateField()),
                ('availability', models.DateTimeField()),
                ('gender', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('DepID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.department')),
            ],
            bases=('Home.user',),
        ),
    ]
